
env_args:
    #env: 'TicTacToe'
    #env: 'Geister'
    #env: 'HungryGeese'
    #env: 'handyrl.envs.parallel_tictactoe'  # specify by path
    env: 'handyrl.envs.3v3snake'

train_args:
    turn_based_training: False
    observation: False
    gamma: 0.8
    forward_steps: 32
    compress_steps: 4
    entropy_regularization: 2.0e-3
    entropy_regularization_decay: 0.3
    update_episodes: 200
    batch_size: 64
    minimum_episodes: 400
    maximum_episodes: 100000
    epochs: 1000
    num_batchers: 2
    eval_rate: 0.1
    worker:
        num_parallel: 6
    lambda: 0.7
    policy_target: 'TD' # 'UPGO' 'VTRACE' 'TD' 'MC'
    value_target: 'TD' # 'VTRACE' 'TD' 'MC'
    eval:
        opponent:
            #- random
            #- MCTSAgent
            #- GreedyAgent
            #- RLAgent
    seed: 0
    restart_epoch: 0
    save_no_episodes: 200
    restart_with_saved_epochs: False
worker_args:
    server_address: '127.0.0.1'
    num_parallel: 6

